### PR TITLE
Migrate to Fluentd v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by okkez** [comment]
See also http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12

**Comment by okkez** [comment]
@kazegusuri Is there any chance to merge this PR?

**Comment by kazegusuri** [comment]
Thank you for ping and sorry for late. I will publish the latest version.

**Comment by okkez** [comment]
Thank you for merging PR and release new version!

**Pull request merged**
